
elasticsearch:
  mem_limit: 100m
  image: elasticsearch
  ports:
    - 9200:9200
  volumes:
    - ./esdata:/usr/share/elasticsearch/data

loggerbot:
  mem_limit: 50m
  image: loggerbot
  volumes:
    - ./scripts:/app
  environment:
    ELASTICSEARCH_URL: http://elasticsearch:9200
  links:
    - elasticsearch
  command: ruby loggerbot.rb

web:
  mem_limit: 50m
  image: loggerbot
  ports:
    - 5600:80
  volumes:
    - ./web:/app
  environment:
    ELASTICSEARCH_URL: http://elasticsearch:9200
  links:
    - elasticsearch
  command: ruby run_sinatra.rb

#kibana:
#  image: kibana:4
#  ports:
#    - 5601:5601
#  links:
#    - elasticsearch
